### ISSUE TITLE
When/how is meant this plugin to be used?

### ISSUE THREAD

**Issue by Vadorequest** [locize/locize-lastused#2]
I'm a bit confused about "when to use this plugin". Is it meant for localhost development? Is it meant for production?

It relies on the `apiKey` to properly function, and this key isn't supposed to be set in production. Does that mean this is only supposed to be used in localhost/testing environments?

Isn't the goal of the plugin kind of limited if that's the case? 🤔 

I don't necessarily go through all possible scenario when working locally, so the "last used" indication will be limited.

Also, it's not clearly stated that this plugin is meant for the development stage and not the production stage (even though it's clearly stated the apiKey must not be shared in production environment).

---

Also, the plugin complains about `apiKey` being null by throwing an error `index.js:1 i18next-lastused :: got "null" in options for apiKey which is invalid.`, which is noisy/boring.

I believe it should be recommended to completely turn off the plugin in non-development environments if that's the intended usage.

---

Please explain your intent with this plugin, as it's currently confusing.

**Comment by jamuhl** [comment]
If that is the case - yes - it's use is limited...but using it in production adds a terrible overhead

```js
if (!isProduction()) {
  i18n.use(locizeLastUsed);
  i18n.use(locizeEditor);
}
```

The plugin helps to find unused key...but as like you say it's not 100% sure you eg. hit all error, validations, ... removing keys based on the lastused date has to be done manually

**Comment by Vadorequest** [comment]
Yeah, I totally understand why you don't want people to use this in production. Thanks, your intentions are clearer now. I suggest you update the readme to reflect this 😃 

It's a better-than-nothing plugin, it helps but we can't completely rely on it to tell us really what's unused, juste what's actually used for real. I'll keep that in mind! :)
