### ISSUE TITLE
Error - Must use import to load ES Module: /var/task/node_modules/locize-lastused/cjs/index.js require() of ES modules is not supported.

### ISSUE THREAD

**Issue by Vadorequest** [locize/locize-lastused#4]
Doing this `const locizeNodeLastUsed = __non_webpack_require__('locize-lastused');` works locally but crashed on Vercel platform with:

> Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /var/task/node_modules/locize-lastused/cjs/index.js require() of ES modules is not supported. 
>
> require() of /var/task/node_modules/locize-lastused/cjs/index.js from /var/task/.next/serverless/pages/[locale]/products.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules. 
>
> Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /var/task/node_modules/locize-lastused/package.json.      
>
> at Object.Module._extensions..js (internal/modules/cjs/loader.js:1174:13)     at Module.load (internal/modules/cjs/loader.js:1002:32)     at Function.Module._load (internal/modules/cjs/loader.js:901:14)     at Module.require (internal/modules/cjs/loader.js:1044:19)     at require (internal/modules/cjs/helpers.js:77:18)     at createI18nextLocizeInstance (/var/task/.next/serverless/pages/[locale]/products.js:4841:32)     at i18nextLocize (/var/task/.next/serverless/pages/[locale]/products.js:4915:29)     at MultiversalAppBootstrap (/var/task/.next/serverless/pages/[locale]/products.js:6835:69)     at d (/var/task/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:498)     at $a (/var/task/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:39:16) {   code: 'ERR_REQUIRE_ESM' }

I wonder if that's to be expected. I'll try doing `__non_webpack_require__('locize-lastused/cjs')` instead.

Note that doing `const locizeNodeLastUsed = __non_webpack_require__('locize-node-lastused');` used to work fine.

**Comment by adrai** [comment]
Yes, same as here: https://github.com/locize/i18next-locize-backend/issues/323#issuecomment-622949927
seems Vercel is not ready to support native esm support of node.js

**Comment by Vadorequest** [comment]
Using /cjs version worked indeed. https://nrn-v1-hyb-mst-aptd-gcms-lcz-sty-c1-1n192xsx6.now.sh/fr/products
